server {
  listen 80;
  server_name qa.yourdomain.com;

  location /allure/ {
    alias /usr/share/nginx/html/allure/;
    index index.html;
    try_files $uri $uri/ /allure/index.html;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}
